broadcast_message:
  icon: mdi:message-arrow-right-outline
  fields:
    message:
      name: Message
      description: Message to send to connected ICE clients
      required: true
      selector:
        text: